defaults:

  # Experiment Setup
  seed: 42
  logroot: logs
  expname: test
  logdir: ""
  filter: '.*'

  # Jax Configuration
  jax:
    platform: gpu
    jit: True
    compute_dtype: bfloat16 # bfloat16, float32
    param_dtype: float32
    prealloc: True
    checks: False
    logical_cpus: 0
    debug: False
    train_devices: [0]
    sync_every: 1
    profiler: False
    transfer_guard: True
    assert_num_devices: -1
    fetch_policy_carry: False
    nvidia_flags: False
    xla_dump: False

  # Experiment Running Mastermind Config
  run:
    script: train
    steps: 1000000 # train steps
    duration: 0
    log_every: 120
    save_every: 900
    eval_every: 180
    log_zeros: True
    from_checkpoint: ''
    usage: {psutil: True, nvsmi: True, gputil: False, malloc: False, gc: False}
    timer: True

  # Models, Training, and Hyperparameters
  diffuser: {stage: 3, thidden: 256, ahidden: 128, hidden: 128, head: 8, group: 8, act: silu}
  beta_sampler: {mode: linear, beta_start: 0.0001, beta_final: 0.02}
  diffuser_steps: 1000
  opt: {lr: 3e-4}
  image_size: [64, 64]
  dir_path: "rolling"
  path_A: ""
  path_B: ""
  batch_size: 16
  loss_scales: {diffuser: 1.0}
  n_classes: 1


tiny:
  diffuser: {thidden: 256, ahidden: 128, hidden: 128, head: 8, group: 8}
  diffuser_steps: 1000

small:
  diffuser: {thidden: 512, ahidden: 256, hidden: 256, head: 8, group: 8}
  diffuser_steps: 1200

large:
  diffuser: {thidden: 1024, ahidden: 512, hidden: 512, head: 8, group: 8}
  diffuser_steps: 1400

monet:
  dir_path: "data/monet_jpg"
  n_classes: 1

photo:
  dir_path: "data/photo_jpg"
  n_classes: 1

elefant:
  dir_path: "elefant"
  n_classes: 1

m2p:
  dir_path: ""
  path_A: "data/monet_jpg"
  path_B: "data/photo_jpg"
  n_classes: 2