defaults:

  # Experiment Setup
  seed: 42
  logroot: logs
  expname: test
  logdir: ""
  filter: '.*'

  # Jax Configuration
  jax:
    platform: gpu
    jit: True
    compute_dtype: bfloat16
    param_dtype: float32
    prealloc: True
    checks: False
    logical_cpus: 0
    debug: False
    train_devices: [0]
    sync_every: 1
    profiler: False
    transfer_guard: True
    assert_num_devices: -1
    fetch_policy_carry: False
    nvidia_flags: False
    xla_dump: False

  # Experiment Running Mastermind Config
  run:
    script: train
    steps: 100000 # train steps
    duration: 0
    log_every: 120
    save_every: 900
    eval_every: 180
    log_zeros: True
    from_checkpoint: ''
    usage: {psutil: True, nvsmi: True, gputil: False, malloc: False, gc: False}
    timer: True

  # Models, Training, and Hyperparameters
  diffuser: {beta_start: 0.0003, beta_final: 0.04, stage: 5, steps: 200, thidden: 64, hidden: 8, head: 4, group: 4, act: silu}
  opt: {lr: 1e-4}
  image_size: [64, 64]
  dir_path: "/dev/null"
  batch_size: 4
  loss_scales: {diffuser: 1.0}


tiny:
  diffuser: {steps: 200, thidden: 64, hidden: 8, head: 4, group: 4}
  batch_size: 4

small:
  diffuser: {steps: 300, thidden: 128, hidden: 16, head: 8, group: 8}
  batch_size: 4

large:
  diffuser: {steps: 400, thidden: 256, hidden: 32, head: 8, group: 8}
  batch_size: 4

monet:
  dir_path: "data/monet_jpg"

photo:
  dir_path: "data/photo_jpg"